# _config.stage.yml

# Server Config

safe: true

source: ./src
destination: ./_site

timezone: Europe/London

future: false
lsi: false
pygments: false
markdown: rdiscount
rdiscount:
  extensions: [smart]

# Site Config

name: Birmingham Post Business Awards 2014

url: /beta
static: /beta/static
media: /beta/media

## Analytics

google_analytics_id:
