# _config.yml

# Server Config

safe: true

source: ./src
destination: ./_site

timezone: Europe/London

future: false
lsi: false
pygments: false
markdown: rdiscount
rdiscount:
  extensions: [smart]

# Site Config

name: Birmingham Post Business Awards 2014

url: http://www.bpbusinessawards.co.uk/2014
static: http://www.bpbusinessawards.co.uk/2014/static
media: http://www.bpbusinessawards.co.uk/2014/media

## Analytics

google_analytics_id:

## Meta

meta:
  author: author
  description: "The Birmingham Post is celebrating the resilience and fortitude of business and industries in Birmingham, West Midlands. Nominate your business for a award."
  keywords:
    - "birmingham post business awards"
    - "midlands business awards"
    - "industry awards"
    - awards
    - nominate
    - birmingham
    - "birmingham business"
    - "busniss awards"
    - "business startup"
    - "small business"
    - "sponsor awards"
    - "increase publicity"
