# _config.yml

# Server Config

safe: true

source: ./src
destination: ./_site
relative_permalinks: false

timezone: Europe/London

future: true
lsi: false
highlighter: null
markdown: rdiscount
rdiscount:
  extensions: [smart]

# Site Config

name: Birmingham Post Business Awards 2014

url:
static: /static
media: /media

## Analytics

google_analytics_id:

## Meta

meta:
  author: author
  description: "The Birmingham Post is celebrating the resilience and fortitude of business and industries in Birmingham, West Midlands. Nominate your business for a award."
  keywords:
    - "birmingham post business awards"
    - "midlands business awards"
    - "industry awards"
    - awards
    - nominate
    - birmingham
    - "birmingham business"
    - "busniss awards"
    - "business startup"
    - "small business"
    - "sponsor awards"
    - "increase publicity"
